"""The boundary: a rule may describe form, never facts about the candidate.

«Всегда пиши, что есть опыт с Kubernetes» is a rule the system must refuse to
store. Not warn about, not obey reluctantly — refuse, at the moment somebody
tries to save it, because a rule that survives saving is a rule the generator
will enforce with a retry loop until the model complies. The whole apparatus
that makes a hard rule trustworthy is what makes a dishonest one dangerous.

**The surface is small, and that is a property of the design rather than luck.**
A rule is structured data, not prose (see :mod:`app.workshop.rules`), so the
only way it can put a *claim* into a document is by naming one. Three fields on
three kinds can do that:

* ``required_keyword.keyword`` — this text must appear in what is written;
* ``required_section.section`` — a section with this heading must exist;
* ``section_item_count.section`` — the same heading, named again.

Everything else — counts, lengths, prohibitions, date formats — constrains the
shape of the document, and a shape cannot be false. A prohibition in particular
is never checked here: «никогда не пиши Kubernetes» is a legitimate rule whether
or not the candidate has ever touched it, because forbidding a name asserts
nothing about anyone.

The rule's ``message`` is not checked either, and that too is structural rather
than an omission: the message is shown to a person and is never rendered into a
prompt. The block the model sees is generated by code from the parameters — see
:mod:`app.workshop.prompt` — so a sentence typed into ``message`` cannot become
an instruction to the model, and there is nothing there to police. A test
asserts that the message never reaches a prompt, because the day it does, this
paragraph becomes false and this module becomes insufficient.

**What "a claim" means here.** A named skill the profile does not hold. The
detection is the skill dictionary the rest of the project already matches on
(:mod:`app.resume.skills`): every one- to three-word window of the text is put
through the canonicaliser, and the ones it recognises are the skills the rule
names. Recognised, and then compared against the profile through the same fold
:mod:`app.letters.context` intersects with — so a rule saying ``Node.js`` and a
resume saying ``nodejs`` are one skill, exactly as they are everywhere else.

Two limits, stated rather than discovered:

* **A skill outside the dictionary is not detected.** The bundled dictionary is
  small (about a hundred entries), so a rule requiring the word "Kubeflow" is
  stored without complaint. What bounds that case is not this module — it is
  that the letter's own honesty check reads the model's declared skills against
  the profile, and that a person reads the letter before it is sent. This
  narrows the hole; it does not close it, and the dictionary growing is what
  closes it further.
* **A recognised skill in an innocent phrase is refused.** "Go" is a skill and
  also a word. A required keyword of «Go-to-market» from a candidate with no Go
  is rejected. The failure is visible and recoverable — the person is told which
  name was read as a skill claim — which is the right direction for a check
  whose other error is a letter claiming experience nobody has.

**With no resume uploaded, everything naming a skill is refused.** There is then
no evidence about the candidate at all, so no claim about them can be supported.
Accepting the rule and checking it later would mean the rules were vetted against
whichever profile happened to exist at generation time, which is the same as not
vetting them.
"""

import re

from app.core.exceptions import AppError
from app.letters.context import fold
from app.resume.skills import default_canonicalizer
from app.workshop.rules import (
    RequiredKeywordParams,
    RequiredSectionParams,
    RuleParams,
    SectionItemCountParams,
)

#: Longest window of words put through the canonicaliser. Three covers every
#: multi-word entry the dictionary holds ("github actions", "yandex cloud",
#: "docker compose") with one to spare; a wider window costs time and finds
#: nothing.
MAX_PHRASE_WORDS = 3

#: What counts as one token of a possible skill name. ``+``, ``#`` and ``.``
#: stay inside it because ``C++``, ``C#`` and ``Node.js`` are spelled with them
#: and splitting there would hide exactly the names the dictionary knows best.
_TOKEN = re.compile(r"[^\W_]+(?:[+#.][^\W_]*)*[+#]*", re.UNICODE)


class RuleRejectedError(AppError):
    """A rule was refused because it would make the system assert an untruth.

    422 rather than 400: the request is well formed and understood, and it is
    the content of the rule that cannot be accepted. The names that caused it
    travel in the problem document, because "rejected" without them is
    unactionable — the person has to know which word was read as a claim.
    """

    status_code = 422
    title = "This rule would require claiming experience the profile does not have"
    problem_type = "rule-requires-untruth"

    def __init__(self, detail: str, *, claims: tuple[str, ...] = ()) -> None:
        super().__init__(detail, claims=list(claims))
        self.claims = claims


def skills_named_in(text: str) -> tuple[str, ...]:
    """Canonical names of every skill the dictionary recognises in this text.

    Windows of one to :data:`MAX_PHRASE_WORDS` tokens, longest first, so
    ``github actions`` is found as one skill rather than as ``github`` plus a
    word. Order of the result follows the text; duplicates are collapsed.
    """
    canonicalizer = default_canonicalizer()
    tokens = _TOKEN.findall(text)
    found: list[str] = []
    for start in range(len(tokens)):
        for size in range(min(MAX_PHRASE_WORDS, len(tokens) - start), 0, -1):
            phrase = " ".join(tokens[start : start + size])
            canonical = canonicalizer.canonicalize(phrase)
            if canonical is not None:
                if canonical not in found:
                    found.append(canonical)
                break
    return tuple(found)


def asserting_text(params: RuleParams) -> tuple[str, ...]:
    """The parts of a rule that put words into the document it governs.

    Empty for every kind that only constrains shape. This function is the list
    from the module docstring, in code, so that adding a kind forces a decision
    about which side of the boundary it falls on.
    """
    match params:
        case RequiredKeywordParams():
            return (params.keyword,)
        case RequiredSectionParams() | SectionItemCountParams():
            return (params.section,)
        case _:
            return ()


def unsupported_claims(params: RuleParams, *, held: frozenset[str]) -> tuple[str, ...]:
    """Skills this rule would have the document claim that the profile lacks.

    ``held`` is the fold of every skill on the profile, as
    :attr:`app.letters.context.LetterContext.possessed` computes it — the same
    keys, so a rule and a letter agree about what counts as the same skill.
    """
    claimed: list[str] = []
    for text in asserting_text(params):
        for skill in skills_named_in(text):
            if fold(skill) not in held and skill not in claimed:
                claimed.append(skill)
    return tuple(claimed)


def ensure_truthful(params: RuleParams, *, held: frozenset[str], has_profile: bool) -> None:
    """Raise :class:`RuleRejectedError` if this rule would require a lie.

    ``has_profile`` is separate from ``held`` being empty on purpose. A profile
    with no skills and no profile at all are both "nothing is supported", but
    only one of them is worth telling the person to fix by uploading a resume,
    and a message that names the wrong one wastes their afternoon.
    """
    claims = unsupported_claims(params, held=held)
    if not claims:
        return

    named = ", ".join(claims)
    if not has_profile:
        raise RuleRejectedError(
            f"the rule names {named}, and there is no resume to support it: rules "
            "describe the form of a document, never facts about the candidate. "
            "Upload a resume first, or write the rule without naming a skill.",
            claims=claims,
        )
    raise RuleRejectedError(
        f"the rule would require the document to claim {named}, which the profile "
        "does not list. Rules describe form, length and prohibitions — not "
        "experience. Add the skill to the profile if the candidate really has it.",
        claims=claims,
    )
