/**
 * Russian labels for the workshop, and the one thing they are not.
 *
 * `describeRule` renders a rule for a person, in Russian. It is **not** what the
 * model is shown: that sentence is `rule.asked_as`, generated by the backend
 * from the same parameters, and the two are displayed side by side on purpose.
 * A rule that does not measure what its author meant is visible in that
 * comparison now rather than in a letter three weeks later.
 */
import type {
  DateFormatPattern,
  ReferenceKind,
  Rule,
  RuleKind,
  RuleParams,
  RuleScope,
  RuleSeverity,
} from '@/types/workshop'

export const KIND_LABELS: Record<RuleKind, string> = {
  section_item_count: 'Количество пунктов в разделе',
  required_section: 'Обязательный раздел',
  required_keyword: 'Обязательное слово или оборот',
  date_format: 'Формат дат',
  forbidden_phrase: 'Запрещённое слово или оборот',
  length: 'Длина',
  no_links: 'Без ссылок',
  no_contact_handles: 'Без email и @',
}

export const SCOPE_LABELS: Record<RuleScope, string> = {
  cv: 'Резюме',
  cover_letter: 'Сопроводительное',
  both: 'И то и другое',
}

export const SEVERITY_LABELS: Record<RuleSeverity, string> = {
  hard: 'Жёсткое',
  soft: 'Мягкое',
}

export const SEVERITY_HINTS: Record<RuleSeverity, string> = {
  hard: 'Проверяется кодом. Пока не выполнено, текст не отдаётся.',
  soft: 'Предупреждение. Текст всё равно отдаётся.',
}

export const REFERENCE_KIND_LABELS: Record<ReferenceKind, string> = {
  cv: 'Резюме',
  cover_letter: 'Сопроводительное',
}

export const DATE_FORMAT_LABELS: Record<DateFormatPattern, string> = {
  'mm.yyyy': '09.2026',
  'mm/yyyy': '09/2026',
  'yyyy-mm': '2026-09',
  yyyy: '2026',
}

/**
 * A counted noun in the case Russian puts it in after «не меньше».
 *
 * Genitive throughout, which is singular after a number ending in 1 (but not
 * 11) and plural after everything else: «не меньше 21 пункта», «не меньше 5
 * пунктов». The backend does the same thing for years in the rule-based letter;
 * the alternative is «не меньше 21 пунктов» in a screen whose whole subject is
 * a person's own careful wording.
 */
type Counted = { one: string; many: string }

const UNITS: Record<'items' | 'characters' | 'words', Counted> = {
  items: { one: 'пункта', many: 'пунктов' },
  characters: { one: 'знака', many: 'знаков' },
  words: { one: 'слова', many: 'слов' },
}

function counted(value: number, unit: Counted): string {
  const tail = value % 10
  const hundred = value % 100
  return tail === 1 && hundred !== 11 ? unit.one : unit.many
}

/** The bounds of a rule that has a floor, a ceiling, or both. */
function bounds(
  minimum: number | null | undefined,
  maximum: number | null | undefined,
  unit: Counted,
): string {
  if (minimum != null && maximum != null) {
    return `от ${String(minimum)} до ${String(maximum)} ${counted(maximum, unit)}`
  }
  if (minimum != null) {
    return `не меньше ${String(minimum)} ${counted(minimum, unit)}`
  }
  if (maximum != null) {
    return `не больше ${String(maximum)} ${counted(maximum, unit)}`
  }
  return unit.many
}

/** One rule as a sentence a person reads. Never sent anywhere. */
export function describeRule(params: RuleParams): string {
  switch (params.kind) {
    case 'section_item_count':
      return `В разделе «${params.section}» — ${bounds(params.minimum, params.maximum, UNITS.items)}`
    case 'required_section':
      return `Обязательно есть раздел «${params.section}»`
    case 'required_keyword':
      return `В тексте обязательно есть «${params.keyword}»${
        params.case_sensitive ? ' (ровно так, с учётом регистра)' : ''
      }`
    case 'date_format':
      return `Все числовые даты записаны как ${DATE_FORMAT_LABELS[params.pattern]}`
    case 'forbidden_phrase':
      return `В тексте никогда не встречается «${params.phrase}»`
    case 'length':
      return `Длина текста — ${bounds(
        params.minimum,
        params.maximum,
        params.unit === 'words' ? UNITS.words : UNITS.characters,
      )}`
    case 'no_links':
      return 'Ни одной ссылки и ни одного адреса сайта'
    case 'no_contact_handles':
      return 'Ни одного email и ни одного ника через @'
  }
}

/** Whether this rule is one a person may edit at all. */
export function isEditable(rule: Rule): boolean {
  return !rule.is_builtin
}
